language: python

jobs:
  include:
    - name: "Python 3.5 on Xenial linux"
      python: 3.5
      os: linux
      dist: xenial
      arch: amd64
    - name: "Python 3.6 on Xenial linux"
      python: 3.6
      os: linux
      dist: xenial
      arch: amd64
    - name: "Python 3.7 on Xenial linux"
      python: 3.7
      os: linux
      dist: xenial
      arch: amd64
    - name: "Python 3.7 on Bionic linux"
      python: 3.7
      os: linux
      dist: bionic
      arch: amd64
    - name: "Python 3.7 on Focal linux"
      python: 3.7
      os: linux
      dist: focal
      arch: amd64
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.5  # Python 3.7 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

# os:
#   - linux

# python:
#   - "3.5"
#   - "3.6"
#   - "3.8"

install:
  - pip3 install --upgrade pip
  - pip3 install numpy
  - pip3 install matplotlib
  - pip3 install scipy
  - pip3 install pandas
  - pip3 install -r requirements.txt
  - pip3 install .
  - pip3 install 'pytest>=3.6'
  - pip3 install pytest-cov coverage coveralls

script:
#  - pytest --cov seglearn
#  - python examples/plot_regression.py || python3 examples/plot_regression.py
  - python examples/plot_forecast.py || python3 examples/plot_forecast.py

after_success:
# - coveralls
  - echo "Successfull."
